### ISSUE TITLE
Out-of-tree builds fail

### ISSUE THREAD

**Issue by rossburton** [ColinIanKing/fwts#2]
```
make[3]: Entering directory '/yocto/ross/build/tmp/work/neoversen1-poky-linux/fwts/20.07.00-r0/build/src/libfwtsiasl'
m4 -P -I../acpica/source/compiler ../acpica/source/compiler/aslparser.y > ../../../fwts-20.07.00/src/libfwtsiasl/aslcompiler.y
m4: cannot open `../acpica/source/compiler/aslparser.y': No such file or directory
```

**Comment by ColinIanKing** [comment]
check you are building it correctly:

autoreconf -ivf
make clean
make

If this fails, please supply the details of your build system (kernel, compiler version and architecture).

**Comment by rossburton** [comment]
I'm building it correctly, with an out-of-tree build.
```
cd fwts
mkdir build
../configure
make
```

This fails because the `src/libfwtsiasl` Makefile is writing generated files to `$srcdir` and trying to read source files from the build directory.

**Comment by ColinIanKing** [comment]
OK - I can reproduce this now, we've never done out-of-tree-builds so the relative path'ing is a bit broken. I'll sort that out

**Comment by ColinIanKing** [comment]
Fix sent for review at fwts-devel mailing list:

https://lists.ubuntu.com/archives/fwts-devel/2021-April/012925.html

**Comment by rossburton** [comment]
Bits like this concern me:
```
+kernelscan_SOURCES = kernelscan.c $(srcdir)/../lib/src/fwts_json.c
```

Is fwts_json.c generated?  If so, it should be written into builddir not srcdir.

**Comment by ColinIanKing** [comment]
It's not generated, it's part of the fwts source

**Comment by ColinIanKing** [comment]
Fix released.
