### ISSUE TITLE
Make -Werrror optional

### ISSUE THREAD

**Issue by rossburton** [ColinIanKing/fwts#4]
-Werror is great for development but the developer doesn't control what version of the compiler and so on is used.  A new compiler, or glibc, or other dependencies can cause warnings which then cause build failures.

Please make -Werror optional.

**Comment by ColinIanKing** [comment]
This is not the official github repository, please re-do the issue report against https://github.com/fwts/

**Comment by rossburton** [comment]
Moved to https://github.com/fwts/fwts/issues/10.
