### ISSUE TITLE
Additional `fwts_tpmlog_event_type` values

### ISSUE THREAD

**Issue by superm1** [ColinIanKing/fwts#6]
In reviewing `lib/include/fwts_tpm.h` against the [latest TCG spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClient_PFP_r1p05_v23_pub.pdf) I found that there are a variety of new event types that are not supported yet by FWTS.

* EV_EFI_PLATFORM_FIRMWARE_BLOB2
* EV_EFI_HANDOFF_TABLES2
* EV_EFI_VARIABLE_BOOT2
* EV_EFI_SPDM_FIRMWARE_BLOB
* EV_EFI_SPDM_FIRMWARE_CONFIG

**Comment by ColinIanKing** [comment]
This is not the official github repository, please re-do the issue report against https://github.com/fwts/

**Comment by superm1** [comment]
Those were actually added as part of b672333fd upstream
